import type { BrandSpec, ContentAsset } from "@/lib/types";

export const brandSpec: BrandSpec = {
  brand_name: "Lumi Beauty",
  voice_spec:
    "Warm, calm, science-literate, plain-spoken, never hype, inclusive.",
  do_words: ["barrier", "routine", "clinically tested", "gentle", "everyday"],
  dont_words: ["miracle", "cure", "anti-aging", "flawless", "detox"],
  approved_claims: [
    "clinically tested for 8 weeks",
    "fragrance-free",
    "supports the skin barrier",
    "dermatologist developed",
    "non-comedogenic",
  ],
  good_examples: [
    "A gentle everyday step for skin that wants a calmer routine, not another promise.",
    "Clinically tested for 8 weeks and made to support the skin barrier without fragrance.",
  ],
  bad_examples: [
    "This miracle serum cures dull skin overnight for a flawless glow.",
    "Detox your face and reverse aging with one viral beauty secret.",
  ],
};

export const northStar =
  "Increase attributed skincare revenue by identifying repeatable content elements that scale efficiently.";

export const minSales = 50;
export const minDays = 5;

export const performanceAssets: ContentAsset[] = [
  {
    id: "a01",
    label: "Founder routine - barrier serum",
    format: "UGC video",
    hook_type: "founder-to-camera",
    length_seconds: 12,
    person: "founder",
    claim: "supports the skin barrier",
    placement: "paid social",
    spend: 18200,
    impressions: 418000,
    hold_rate: 0.46,
    ctr: 0.031,
    in_video_atc: 5720,
    attributed_sales: 982,
    aov: 58,
    attributed_revenue: 56956,
    days_live: 28,
  },
  {
    id: "a02",
    label: "Founder myth - fragrance-free",
    format: "UGC video",
    hook_type: "founder-to-camera",
    length_seconds: 11,
    person: "founder",
    claim: "fragrance-free",
    placement: "paid social",
    spend: 14500,
    impressions: 356000,
    hold_rate: 0.43,
    ctr: 0.029,
    in_video_atc: 4490,
    attributed_sales: 810,
    aov: 53,
    attributed_revenue: 42930,
    days_live: 24,
  },
  {
    id: "a03",
    label: "Founder reset - clinical proof",
    format: "UGC video",
    hook_type: "founder-to-camera",
    length_seconds: 13,
    person: "founder",
    claim: "clinically tested for 8 weeks",
    placement: "paid social",
    spend: 16000,
    impressions: 392000,
    hold_rate: 0.45,
    ctr: 0.03,
    in_video_atc: 5010,
    attributed_sales: 724,
    aov: 55,
    attributed_revenue: 39820,
    days_live: 21,
  },
  {
    id: "a04",
    label: "Founder shelf - barrier check",
    format: "UGC video",
    hook_type: "founder-to-camera",
    length_seconds: 14,
    person: "founder",
    claim: "dermatologist developed",
    placement: "paid social",
    spend: 12200,
    impressions: 301000,
    hold_rate: 0.41,
    ctr: 0.027,
    in_video_atc: 3790,
    attributed_sales: 641,
    aov: 56,
    attributed_revenue: 35896,
    days_live: 19,
  },
  {
    id: "a05",
    label: "Customer quote - calmer routine",
    format: "UGC video",
    hook_type: "customer quote",
    length_seconds: 18,
    person: "customer",
    claim: "supports the skin barrier",
    placement: "paid social",
    spend: 9100,
    impressions: 214000,
    hold_rate: 0.34,
    ctr: 0.022,
    in_video_atc: 2060,
    attributed_sales: 334,
    aov: 54,
    attributed_revenue: 18036,
    days_live: 18,
  },
  {
    id: "a06",
    label: "Studio demo - non-comedogenic",
    format: "studio video",
    hook_type: "product demo",
    length_seconds: 22,
    person: "model",
    claim: "non-comedogenic",
    placement: "paid social",
    spend: 9800,
    impressions: 241000,
    hold_rate: 0.29,
    ctr: 0.018,
    in_video_atc: 1510,
    attributed_sales: 263,
    aov: 56,
    attributed_revenue: 14728,
    days_live: 20,
  },
  {
    id: "a07",
    label: "Carousel - dermatologist notes",
    format: "carousel",
    hook_type: "problem-then-fix",
    length_seconds: 0,
    person: "none",
    claim: "dermatologist developed",
    placement: "product page",
    spend: 4700,
    impressions: 112000,
    hold_rate: 0.24,
    ctr: 0.021,
    in_video_atc: 900,
    attributed_sales: 184,
    aov: 57,
    attributed_revenue: 10488,
    days_live: 16,
  },
  {
    id: "a08",
    label: "Email story - fragrance-free",
    format: "carousel",
    hook_type: "customer quote",
    length_seconds: 0,
    person: "customer",
    claim: "fragrance-free",
    placement: "email",
    spend: 1200,
    impressions: 64000,
    hold_rate: 0.19,
    ctr: 0.026,
    in_video_atc: 780,
    attributed_sales: 171,
    aov: 50,
    attributed_revenue: 8550,
    days_live: 12,
  },
  {
    id: "a09",
    label: "Product demo - everyday gel",
    format: "studio video",
    hook_type: "product demo",
    length_seconds: 19,
    person: "model",
    claim: "fragrance-free",
    placement: "product page",
    spend: 6100,
    impressions: 145000,
    hold_rate: 0.31,
    ctr: 0.02,
    in_video_atc: 1340,
    attributed_sales: 247,
    aov: 52,
    attributed_revenue: 12844,
    days_live: 15,
  },
  {
    id: "a10",
    label: "Studio glam - launch discount",
    format: "studio video",
    hook_type: "discount",
    length_seconds: 16,
    person: "model",
    claim: "none",
    placement: "paid social",
    spend: 12600,
    impressions: 321000,
    hold_rate: 0.22,
    ctr: 0.012,
    in_video_atc: 610,
    attributed_sales: 118,
    aov: 46,
    attributed_revenue: 5428,
    days_live: 22,
  },
  {
    id: "a11",
    label: "Static jar - discount code",
    format: "static image",
    hook_type: "discount",
    length_seconds: 0,
    person: "none",
    claim: "none",
    placement: "paid social",
    spend: 5200,
    impressions: 138000,
    hold_rate: 0.12,
    ctr: 0.009,
    in_video_atc: 260,
    attributed_sales: 61,
    aov: 43,
    attributed_revenue: 2623,
    days_live: 14,
  },
  {
    id: "a12",
    label: "Static shelf - clean lineup",
    format: "static image",
    hook_type: "product demo",
    length_seconds: 0,
    person: "none",
    claim: "none",
    placement: "paid social",
    spend: 6800,
    impressions: 152000,
    hold_rate: 0.13,
    ctr: 0.01,
    in_video_atc: 340,
    attributed_sales: 79,
    aov: 45,
    attributed_revenue: 3555,
    days_live: 18,
  },
  {
    id: "a13",
    label: "Derm edit - barrier serum teaser",
    format: "UGC video",
    hook_type: "founder-to-camera",
    length_seconds: 10,
    person: "founder",
    claim: "supports the skin barrier",
    placement: "paid social",
    spend: 900,
    impressions: 28000,
    hold_rate: 0.52,
    ctr: 0.036,
    in_video_atc: 410,
    attributed_sales: 38,
    aov: 61,
    attributed_revenue: 2318,
    days_live: 3,
  },
  {
    id: "a14",
    label: "Creator quick quote - clinical test",
    format: "UGC video",
    hook_type: "customer quote",
    length_seconds: 9,
    person: "customer",
    claim: "clinically tested for 8 weeks",
    placement: "paid social",
    spend: 650,
    impressions: 19000,
    hold_rate: 0.47,
    ctr: 0.032,
    in_video_atc: 280,
    attributed_sales: 27,
    aov: 59,
    attributed_revenue: 1593,
    days_live: 6,
  },
];
